### ISSUE TITLE
easyrpg theme is incomplete

### ISSUE THREAD

**Issue by 25minutes** [dale-personal/es-comicbookTheme-2.0#1]
ComicbookTheme has always been my favorite. Unfortunately it's not updated for a long time, and it doesn't have the themes for many new systems. 

I'm really happy to find this fork. Finally I can switch back to ComicbookTheme again. Your new themes are awesome! All themes are working great expect easyrpg. It seems this one is incomplete. Could you please update it when you are convenient?

**Comment by dale-personal** [comment]
@25minutes - I've added some assets for Easy RPG.
